version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    command: ["server"]
    volumes:
      - ./src/:/popper-app/src/
      - ./data/:/popper-app/data/
    environment:
      - API_KEY=demo
